-- Run this in Supabase SQL Editor.
-- Note: this migration recreates messaging tables and resets previous messages.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  phone text unique,
  display_name text,
  access_code text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists access_code text;

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  is_direct boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key (conversation_id, user_id)
);

alter table public.conversation_members
  add column if not exists last_read_at timestamptz;

drop table if exists public.messages cascade;
create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_phone text,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

create or replace function public.is_member_of_conversation(target_conversation_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.conversation_members cm
    where cm.conversation_id = target_conversation_id
      and cm.user_id = auth.uid()
  );
$$;

grant execute on function public.is_member_of_conversation(uuid) to authenticated;

-- Profiles policies
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Conversation policies
drop policy if exists "conversations_select_member" on public.conversations;
create policy "conversations_select_member"
  on public.conversations
  for select
  to authenticated
  using (public.is_member_of_conversation(id));

drop policy if exists "conversations_insert_authenticated" on public.conversations;
create policy "conversations_insert_authenticated"
  on public.conversations
  for insert
  to authenticated
  with check (true);

-- Membership policies
drop policy if exists "members_select_own_conversations" on public.conversation_members;
create policy "members_select_own_conversations"
  on public.conversation_members
  for select
  to authenticated
  using (public.is_member_of_conversation(conversation_id));

-- Inserts of members are done via function below.
drop policy if exists "members_no_direct_insert" on public.conversation_members;
create policy "members_no_direct_insert"
  on public.conversation_members
  for insert
  to authenticated
  with check (false);

drop policy if exists "members_update_own_read" on public.conversation_members;
create policy "members_update_own_read"
  on public.conversation_members
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Message policies
drop policy if exists "messages_select_member" on public.messages;
create policy "messages_select_member"
  on public.messages
  for select
  to authenticated
  using (public.is_member_of_conversation(conversation_id));

drop policy if exists "messages_insert_member" on public.messages;
create policy "messages_insert_member"
  on public.messages
  for insert
  to authenticated
  with check (
    auth.uid() = sender_id
    and public.is_member_of_conversation(conversation_id)
  );

drop policy if exists "messages_delete_own" on public.messages;
create policy "messages_delete_own"
  on public.messages
  for delete
  to authenticated
  using (
    auth.uid() = sender_id
    and public.is_member_of_conversation(conversation_id)
  );

create or replace function public.start_dm_chat(peer_phone text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  peer uuid;
  existing_conversation uuid;
  new_conversation uuid;
begin
  if me is null then
    raise exception 'Not authenticated';
  end if;

  select p.id into peer
  from public.profiles p
  where p.phone = peer_phone
  limit 1;

  if peer is null then
    raise exception 'No existe un usuario con ese numero';
  end if;

  if peer = me then
    raise exception 'No puedes abrir chat contigo mismo';
  end if;

  select cm1.conversation_id into existing_conversation
  from public.conversation_members cm1
  join public.conversation_members cm2
    on cm1.conversation_id = cm2.conversation_id
  join public.conversations c
    on c.id = cm1.conversation_id
  where cm1.user_id = me
    and cm2.user_id = peer
    and c.is_direct = true
  limit 1;

  if existing_conversation is not null then
    return existing_conversation;
  end if;

  insert into public.conversations (is_direct)
  values (true)
  returning id into new_conversation;

  insert into public.conversation_members (conversation_id, user_id)
  values (new_conversation, me), (new_conversation, peer);

  return new_conversation;
end;
$$;

grant execute on function public.start_dm_chat(text) to authenticated;

-- Storage bucket for chat photos
insert into storage.buckets (id, name, public)
values ('chat-media', 'chat-media', true)
on conflict (id) do update set public = true;

drop policy if exists "chat_media_read_public" on storage.objects;
create policy "chat_media_read_public"
  on storage.objects
  for select
  to authenticated
  using (bucket_id = 'chat-media');

drop policy if exists "chat_media_insert_authenticated" on storage.objects;
create policy "chat_media_insert_authenticated"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'chat-media');
